language: node_js
compiler: gcc
env:
  global:
    - NODE_LIBPNG_SKIP_BINARY_DOWNLOAD_FOR_CI=true
jobs:
  include:
    - stage: build
      node_js: "10"
      os: linux
    - stage: build
      node_js: "12"
      os: linux
    - stage: build
      node_js: "14"
      os: linux
    - stage: build
      node_js: "15"
      os: linux
    - stage: build
      node_js: "16"
      os: linux
    - stage: build
      node_js: "10"
      os: osx
    - stage: build
      node_js: "12"
      os: osx
    - stage: build
      node_js: "14"
      os: osx
    - stage: build
      node_js: "15"
      os: osx
    - stage: build
      node_js: "16"
      os: osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - make
      - git
before_install:
  - npm install -g yarn
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-7";
      export CXX="g++-7";
      export LINK="gcc-7";
      export LINKXX="g++-7";
    fi
  - node --version
  - yarn --version
script:
  - make
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      CFLAGS="-Wno-implicit-function-declaration" CPPFLAGS="-DPNG_ARM_NEON_OPT=0" yarn prebuild --arch=arm64;
      ARCH="arm64" yarn postbuild;
    fi
after_script:
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache: yarn
deploy:
  provider: releases
  api_key:
    secure: "JiSof20geLe50cqCVXJKYabfs7t4PiobD6uA2BZo4h2GM5U6JcuGhzxWZfz7tNvSwAG1Y01iPz+rS7R8rSZfwtqq5qWyPLt29sM1T9ivuunD3GDRFppDIIsZCaHABg3xP3CMYcwuN9S3thkjHMcOAKR+9SlQNyAWilHltZVtOa+ftwlkTzoIyAp3HkSFBbBT98BPi65oXUCVxR3mJqCoKZnTX0wl7RMpEFdCsZ1XmefdPEpFc7o2UhDRbl7RtcplybocEFzdcv7+d80rMCR0xG+mB8IpeuGdMfmXvX3DJO09dO3/yBhXnuyePZ1EgcZ8CLD/f+hQU5aFao2e8WaYrWPaxWkIfqWfkl0lOwzthK4sTxwkcFpK2BqxowDEjbB2POCNaYsabDvDpBSm9Fwp5aPOeqdzYVbKWPoYcbj8udacpst8S0s8kVis3ZmTDNzl+OR6EHlwubrUtQJRWZGGRg2JHReR2t/WPcQcwKF6t8q53DGdxD+xaYAq6MGjdmCM4WaparIGvUqWap38XjuTZar9Vc6eFqcPuM3R2QpInA44RIHJ0LjnVEn4rk6rduzT0orkgCTlvxeCOxOY9iHSGrKfmfTTf4Hp8klS0jSmxIBvsQ7gJyrSQiSogNnKg5nF4PYZUYVkwep0VhKKplOHj6y0OKZM14eoZNHzLXQqI/0="
  file_glob: true
  file: "node-libpng-*-*-*.node"
  skip_cleanup: true
  on:
    tags: true
